### ISSUE TITLE
학생 이동 관리 기능 추가 관련 회의

### ISSUE THREAD

**Issue by WoungSub-Byun** [Doran-Doran-development/DoranDoran-Server#50]
> 학생 이동 관리 기능 추가
- 선생님들이 확인하시는 용도이기 때문에 앱으로 해당 뷰 볼 수 있게 하는 것도 좋을 듯합니다. (아니면 반응형 웹)
- 기존에 개발된 기능에서도 바뀌는 게 있을 수 있으니 회의가 필요할 것 같습니다.

**Comment by hanbin8269** [comment]
오늘 저녁 먹구 10교시쯤에 모이는게 어떨까요?

**Comment by hanbin8269** [comment]
#51 이슈에서 통합적으로 논의하도록 했습니다. 이 이슈는 닫겠습니다 👍
