### ISSUE TITLE
예약 관련 API 명세서 작성

### ISSUE THREAD

**Issue by seojinsarejj** [Doran-Doran-development/DoranDoran-Server#58]

**Comment by seojinsarejj** [comment]
기능 명세서의 담임 회의실 예약 관리 부분을 위해 특정 학년의 예약 목록만 불러주는 API가 필요할 거 같아요

**Comment by WoungSub-Byun** [comment]
> 기능 명세서의 담임 회의실 예약 관리 부분을 위해 특정 학년의 예약 목록만 불러주는 API가 필요할 거 같아요
오 놓쳤었네요 추가하겠습니다~~😊😊

**Comment by WoungSub-Byun** [comment]
그런데 특정 학년의 예약 목록이라고 하면 reserver_id의 학년인가요 아니면 팀원 전체 중 한명이라도 는 학년인가요??

**Comment by seojinsarejj** [comment]
> 그런데 특정 학년의 예약 목록이라고 하면 reserver_id의 학년인가요 아니면 팀원 전체 중 한명이라도 는 학년인가요??

아 팀원들의 학년이 다른 경우도 존재하겠군요 그 부분은 다시 회의를 해봐야 할 것 같습니다. 새로 이슈 추가할게요

**Comment by hanbin8269** [comment]
다 읽어봤습니다!

- 전 버전과 달리 URI 이름을 `/reservations/<room_id>`와 같이 명사를 사용하면 좋을거같아요
- `/reserve/<grade>` 을 `/reserve?grade=<grade>` 로 필터링 하는게 좋을거같아요~ room_id로 조회하는 것도 마찬가지로요
![image](https://user-images.githubusercontent.com/58972963/110751575-60bb1000-8287-11eb-8117-453bbedb4303.png)
