### ISSUE TITLE
외출 관련 API 명세서 작성

### ISSUE THREAD

**Issue by seojinsarejj** [Doran-Doran-development/DoranDoran-Server#59]

**Comment by hanbin8269** [comment]
다 읽어 봤습니다.
- 외출 URI의 이름이 `out` 이니 가독성이 떨어지는 기분이 듭니다.. `out-requests` 는 어떨까요?
- `/out/<grade>/<class>`를 `/out?grade=<grade>&class=<class>` 형식으로 해야 합니다. (class -> homeroom 도 고려해주세요)
