### ISSUE TITLE
전체적인 스키마 작성

### ISSUE THREAD

**Issue by hanbin8269** [Doran-Doran-development/DoranDoran-Server#61]
Aquery 툴을 사용하도록 하자
## TODO
- User Schema 작성
- Room Schema  작성
- Reserve_Room Schema 작성
- Out Schema 작성
- Team Schema 작성

**Comment by hanbin8269** [comment]
![image](https://user-images.githubusercontent.com/58972963/110409966-75eb3f80-80cb-11eb-9e5b-35e16619b017.png)

- User id 를 Auto Increment가 아닌 UUID를 사용하기로 해서 자료형을 바꿔주었어요!
- 반 정보를 class로 표현하는건 파이썬 class랑 겹쳐서 혼동이 올수 있어 group로 바꾸었어요!
- 활성화 된 유저인지 확인하기 위한 is_active 컬럼을 추가했어요

**Comment by hanbin8269** [comment]
본인 담당 스키마 변경 사항 확인해주시구 코멘트 하나씩 달아주세용 ㅎㅎ @icefirebear @seojinsarejj

**Comment by WoungSub-Byun** [comment]
- 현재 노션에 있는 AqueryTool 링크는 읽기전용 권한을 부여해놔서 직접적인 작성이 불가능합니다.
지금 권한 수정해드릴테니 다시 작성해주시기 바랍니다!😃
- 그리고 uuid로 pk를 바꾼 이유가 있을까요??💁

**Comment by hanbin8269** [comment]
> * 그리고 uuid로 pk를 바꾼 이유가 있을까요??💁

- 첫번째로 학교 서비스라는 점에서 여러 데이터베이스에서 학생의 정보를 공유 할 수 있는 상황이 나올 수 있는데 **UUID**를 사용하면 중복을 피할 수 있습니다!
- 또한 `users/1` , `users/2`, `users/3` 이렇게 하나씩 올려가며 조회하는 비정상적인 접근을 막을 수 있습니다!

**Comment by WoungSub-Byun** [comment]
아하 좋습니다👍 
그럼 `User`테이블은 `uuid` 적용하는 것으로 하고 다른 테이블의 PK는 `AI` 유지할까요??

**Comment by hanbin8269** [comment]
> 아하 좋습니다👍
> 그럼 `User`테이블은 `uuid` 적용하는 것으로 하고 다른 테이블의 PK는 `AI` 유지할까요??

네네 :)

**Comment by hanbin8269** [comment]
![image](https://user-images.githubusercontent.com/58972963/110580574-51b35f80-81ac-11eb-990b-9513cfd56b75.png)

- 반 정보를 나타내는 컬럼이 직관적으로 느껴지기 위해 homeroom으로 변경했습니다
- User를 Student와 Teacher 로 분리했습니다.
