### ISSUE TITLE
예약 시 팀원들의 학년이 모두 다른 경우 처리 방법

### ISSUE THREAD

**Issue by seojinsarejj** [Doran-Doran-development/DoranDoran-Server#62]
예약 시 팀원들의 학년이 모두 다른 경우 예약자 학년에 예약 목록이 뜨게 할지 팀원 개개인 모두의 학년에 보여 질지 결정해야 할 것 같습니다.

**Comment by hanbin8269** [comment]
회의 결과 팀장의 학년으로만 요청이 가도록 했습니다
